name: update-daily-quote

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-phrase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PERSONAL_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Generate daily quote
        run: |
          node -e "
            const fs = require('fs');
            const path = './frases.json';

            if (!fs.existsSync(path)) {
              throw new Error('frases.json file not found.');
            }

            const frases = JSON.parse(fs.readFileSync(path, 'utf8'));
            if (!Array.isArray(frases) || frases.length === 0) {
              throw new Error('frases.json is empty or not a valid array.');
            }

            const today = new Date();
            const dayOfYear = Math.floor((today - new Date(today.getFullYear(), 0, 0)) / 86400000);
            const quote = frases[dayOfYear % frases.length];

            if (!quote) {
              throw new Error('Unable to get quote for the current day');
            }

            fs.writeFileSync('frase-do-dia.txt', quote, 'utf8');
          "

      - name: Commit and push
        env:
          PERSONAL_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
        run: |
          git config user.name "Mariana Viana"
          git config user.email "marianaviana@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${MY_PERSONAL_TOKEN}@github.com/${{ github.repository }}
          git add frase-do-dia.txt
          git commit -m "chore: update phrase of the day: $(date +'%d/%m/%Y')" || echo "nothing to commit"
          git push