name: Atualizar Frase do Dia

on:
  schedule:
    - cron: '1 3 * * *' # Todos os dias às 00:01 no horário de Brasília (03:01 UTC)
  workflow_dispatch:    # Permite rodar manualmente também

jobs:
  update-phrase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Gerar frase do dia
        run: |
          node -e "
            const fs = require('fs');
            const path = './frases.json';

            if (!fs.existsSync(path)) {
              throw new Error('Arquivo frases.json não encontrado.');
            }

            const frases = JSON.parse(fs.readFileSync(path, 'utf8'));
            if (!Array.isArray(frases) || frases.length === 0) {
              throw new Error('frases.json está vazio ou não é um array válido.');
            }

            const hoje = new Date();
            const diaDoAno = Math.floor((hoje - new Date(hoje.getFullYear(), 0, 0)) / 86400000);
            const frase = frases[diaDoAno % frases.length];

            if (!frase) {
              throw new Error('Não foi possível obter a frase para o dia atual.');
            }

            fs.writeFileSync('frase-do-dia.txt', frase, 'utf8');
          "

      - name: Commit e push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add frase-do-dia.txt
          git commit -m "Update phrase of the day: $(date +'%d/%m/%Y')" || echo "Nothing to commit"
          git push